language: rust

sudo: required

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

branches:
  only:
    - master

script:
  - |
      cargo test --verbose &&
      cargo bench --verbose 
